version: '3.1'

services:

  db:
    container_name: pg-docker-assoc
    image: postgres
    restart: always
    env_file:
      - ./config/.env.test
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    container_name: pg-adminer-assoc
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8089:8080
